version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: yii2_nginx
    ports:
      - "8080:80"
    volumes:
      - ../yii2basic:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - redis

  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:7.4-fpm
    container_name: yii2_php
    volumes:
      - ../yii2basic:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: yii2_redis
    ports:
      - "6379:6379"